config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :achievements
  root to: 'welcome#index'

end

app/models/achievement.rb
class Achievement < ApplicationRecord
  include ActiveModel::ForbiddenAttributesProtection
  has_many :events
  belongs_to :user

  validates :title, presence: true
  validates :user, presence: true
  validates :title, uniqueness: {
    scope: :user_id,
    message: ('you can\'t have two achievements with the same title')
  }

  enum privacy: [ :public_access, :private_access, :friends_access ]

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  private


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :achievements
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :owners_only, only: [:edit, :update, :destroy]

  def index
    @achievements = Achievement.public_access
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = current_user.achievements.new(achievement_params)
    if @achievement.save
      redirect_to achievements_url(@achievement), notice: 'Achievement has been created'
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @achievement.update(achievement_params)
      redirect_to achievement_path(@achievement)
    else
      render :edit
    end
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_path
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :features)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    if current_user != @achievement.user
      redirect_to achievements_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k,v| [k.split('_').first.capitalize, k] }] %>

	<%= f.input :features, label: 'Featured achievement' %>

<%= f.input :cover_image, as: :file %>
<%= f.submit 'Create Achievement', class: 'btn btn-primary' %>
<% end %>

app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
	<%= @achievement.description_html.html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">I-Rock</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
          <li><%= link_to 'New Achievement', new_achievement_path %></li>
        </li>
      </ul>
    </div>
  </div>
</nav>

 <% if flash[:notice] %>
  <div class="alert alert-info"> <%= flash[:notice] %></div>
 <% end %>

     <%= yield %>
</div>


  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>